/**
 * @vitest-environment happy-dom
 */
/**
 * Property Tests: Password Strength Indicator Visibility
 *
 * Feature: auth-screens-redesign, Property 3: Password Strength Indicator Visibility
 *
 * For any string of length 0–30, the password strength indicator is visible
 * (display !== 'none') when the string is non-empty, and hidden (display === 'none')
 * when the string is empty.
 *
 * **Validates: Requirements 7.1**
 */
import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { createPasswordStrengthIndicator } from '../PasswordStrengthIndicator';

describe('Property 3: Password Strength Indicator Visibility', () => {
  /**
   * **Validates: Requirements 7.1**
   *
   * For any string generated by fc.string({ minLength: 0, maxLength: 30 }),
   * after calling update(s):
   * - If s is non-empty, the indicator element is visible (display !== 'none')
   * - If s is empty, the indicator element is hidden (display === 'none')
   */
  it('indicator is visible for non-empty strings and hidden for empty strings', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 0, maxLength: 30 }),
        (s) => {
          const { element, update } = createPasswordStrengthIndicator();

          update(s);

          if (s.length > 0) {
            expect(element.style.display).not.toBe('none');
          } else {
            expect(element.style.display).toBe('none');
          }
        }
      ),
      { numRuns: 100 }
    );
  });
});
