/**
 * @vitest-environment happy-dom
 */
/**
 * Property Tests: Password Strength Evaluation Correctness
 *
 * Feature: auth-screens-redesign, Property 2: Password Strength Evaluation Correctness
 *
 * For any password string generated by fast-check, each criterion in
 * evaluatePasswordStrength(s) matches the corresponding regex test on s.
 *
 * **Validates: Requirements 7.3, 7.4**
 */
import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { evaluatePasswordStrength } from '../PasswordStrengthIndicator';

describe('Property 2: Password Strength Evaluation Correctness', () => {
  /**
   * **Validates: Requirements 7.3, 7.4**
   *
   * For any password string of length 0-30, evaluatePasswordStrength returns
   * criteria that exactly match the corresponding regex tests on the input.
   */
  it('each criterion matches the corresponding regex test on the input string', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 0, maxLength: 30 }),
        (s) => {
          const result = evaluatePasswordStrength(s);

          expect(result.uppercase).toBe(/[A-Z]/.test(s));
          expect(result.lowercase).toBe(/[a-z]/.test(s));
          expect(result.number).toBe(/[0-9]/.test(s));
          expect(result.symbol).toBe(/[^a-zA-Z0-9]/.test(s));
          expect(result.minLength).toBe(s.length >= 8);
        }
      ),
      { numRuns: 100 }
    );
  });
});
